<a href="https://colab.research.google.com/github/ykitaguchi77/Laboratory_course/blob/master/1.%20Google%20colab%E3%81%A7%E7%94%BB%E5%83%8F%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Colaboratoryで画像を表示する
Google driveをマウントする。
左のタブ → ファイル → ドライブをマウントをクリックするとスクリプトが表示される

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#Open CVを用いる方法
※画像のパスは、左のタブでファイルを右クリックするとコピーできる（便利！）

In [ ]:
#サポートパッチのインポート
from google.colab.patches import cv2_imshow
import cv2

#画像のインポート

img = cv2.imread('/content/drive/My Drive/AI_laboratory_course/goldenretriever-3724972_640.jpg', cv2.IMREAD_UNCHANGED)
cv2_imshow(img)

#PILLOWを用いる方法
画像の演算を行うときにはこれを使う<br>
Matplotlibはグラフを作成するモジュール

In [ ]:
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt

img = Image.open("/content/drive/My Drive/AI_laboratory_course/goldenretriever-3724972_640.jpg")
plt.imshow(np.array(img))
plt.show()

イメージのサイズ確認
RGBを一つの単位として、960×640個並んでいる（ピクセル数に対応）

In [ ]:
print(img.size)
print(np.array(img))

(960, 640)
[[[  3  91 115]
  [  2  89 116]
  [  1  88 115]
  ...
  [ 63 137 150]
  [ 55 129 142]
  [ 50 124 137]]

 [[  2  89 116]
  [  0  87 114]
  [  0  87 114]
  ...
  [ 66 140 153]
  [ 63 137 150]
  [ 58 132 145]]

 [[  3  90 117]
  [  1  88 115]
  [  1  88 115]
  ...
  [ 66 140 153]
  [ 61 135 148]
  [ 53 127 140]]

 ...

 [[ 29  47  51]
  [ 25  43  47]
  [ 26  44  48]
  ...
  [110 111 103]
  [113 114 106]
  [113 114 106]]

 [[ 27  45  49]
  [ 24  42  46]
  [ 27  42  47]
  ...
  [108 109 101]
  [110 111 103]
  [105 106  98]]

 [[ 26  41  46]
  [ 25  40  45]
  [ 28  43  48]
  ...
  [ 99 100  92]
  [104 105  97]
  [103 104  96]]]


IPythonをインポートする方法もある

In [ ]:
from IPython.display import display
from PIL import Image

img = Image.open("/content/drive/My Drive/AI_laboratory_course/goldenretriever-3724972_640.jpg")
display(img)