<a href="https://colab.research.google.com/github/ykitaguchi77/Laboratory_course/blob/master/5.%20OPEN%20CV%E3%82%92%E7%94%A8%E3%81%84%E3%81%9F%E9%A1%94%E8%AA%8D%E8%AD%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#OPEN CVを用いた顔認識

Google driveをマウントする

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#OPEN CVを用いて画像を表示

In [4]:
#サポートパッチのインポート
from google.colab.patches import cv2_imshow
import cv2

In [ ]:
#画像のインポート

img = cv2.imread('/content/drive/My Drive/AI_laboratory_course/shuugou.jpg', cv2.IMREAD_UNCHANGED)
cv2_imshow(img)

In [ ]:
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2_imshow(img_gray)

#カスケード型分類器のインポート

In [7]:
face_cascade_path = '/content/drive/My Drive/AI_laboratory_course/haarcascade_frontalface_alt.xml'
eye_cascade_path = '/content/drive/My Drive/AI_laboratory_course/haarcascade_eye.xml'

face_cascade = cv2.CascadeClassifier(face_cascade_path)
eye_cascade = cv2.CascadeClassifier(eye_cascade_path)

faces = face_cascade.detectMultiScale(img_gray)
print(faces)

[[520  78  63  63]
 [402 126  59  59]
 [310 110  55  55]
 [207 114  56  56]
 [104 108  63  63]
 [449 172  72  72]
 [171 189  70  70]]


#顔と目をマーク

In [ ]:
for x, y, w, h in faces:
    cv2.rectangle(img, (x, y), (x + w, y + h), (255, 0, 0), 2)
    face = img[y: y + h, x: x + w]
    face_gray = img_gray[y: y + h, x: x + w]
    eyes = eye_cascade.detectMultiScale(face_gray)
    for (ex, ey, ew, eh) in eyes:
        cv2.rectangle(face, (ex, ey), (ex + ew, ey + eh), (0, 255, 0), 2)

cv2_imshow(img)


画像を保存

In [9]:
cv2.imwrite('/content/drive/My Drive/AI_laboratory_course/opencv_face_detect_rectangle.jpg', img)

True

#Dlibを用いた顔認識

In [ ]:
from google.colab.patches import cv2_imshow
import cv2
import matplotlib.pyplot as plt
import math
from PIL import Image
import numpy as np
import dlib
from imutils import face_utils

predictor_path = '/content/drive/My Drive/AI_laboratory_course/shape_predictor_68_face_landmarks.dat'
predictor = dlib.shape_predictor(predictor_path)
detector = dlib.get_frontal_face_detector()

# 画像読込み
img = cv2.imread('/content/drive/My Drive/AI_laboratory_course/face.jpg', cv2.IMREAD_UNCHANGED)

if img is None:
    print('画像が見つかりません')
    exit()

rects = detector(img, 1)
if len(rects) == 0:
    print('顔が抽出されませんでした')
    exit()

for rect in rects:
    for idx,p in enumerate(predictor(img,rect).parts()): 
        x = p.x
        y = p.y
        cv2.circle(img, (x,y),2, (0,255,0), thickness= 3)
        cv2.putText(img,str(idx) , (x + 3, y+3), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), thickness=1)

cv2_imshow(img)

In [12]:
dets = detector(img[:, :, ::-1])
parts = predictor (img, dets[0]).parts()

#parts[33]の座標を表示する
print(parts[33].x)
print(parts[33].y)
print(parts[33])

523
686
(523, 686)


In [ ]:
#全partsの座標を表示
for i, coordinate in enumerate (parts, 1):
    print (i, coordinate)

#演習問題　
右眼の周囲を切り抜いて表示するスクリプトを作ってみよう

例： <br>
X座標　parts[17] ～ parts[27]  <br>
Y座標　parts[19] ～ parts[28]  <br>
<br>
ヒント：<br>
画像の切り出し<br>
img1 = img [200 : 500, 100: 700]